### ISSUE TITLE
exif orientation tag not being respected

### ISSUE THREAD

**Issue by angelmanst** [bpatrik/pigallery2#11]
When seeing thumbnails and pictures in portrait that haven't been rotated (but have the exif orientation tag to rotate).
As you can see in the attached printscreen, two of the pictures should be rotated because they've been taken in portrait mode.
![rotate_issue](https://user-images.githubusercontent.com/42786558/44752525-277c8380-ab13-11e8-83d8-f8be6df680fd.png)

From the first picture I have the following on the exif data:
exiftran -d 2016-07-28\ 09.34.32.jpg
2016-07-28 09.34.32.jpg
   ifd 0
      0x0112  Orientation                    Right-top
      0x011a  X-Resolution                   72
      0x011b  Y-Resolution                   72
      0x0128  Resolution Unit                Inch
      0x0213  YCbCr Positioning              Centered

When I use exiftran to process the picture with the "-a" option to apply automatic rotation according to the orientation tag, the pictures start appearing in the correct orientation (if I change their name because I'm assuming that since the thumbnail has been created before the change, pigallery2 woun't recreate the thumbnail and the thumbnail still appears in landscape).

**Comment by bpatrik** [comment]
Hi, 

Thank you the valuable feedback. As far as i understand there are 2 bugs. I shall fix both of them.
I got a bit busy lately (and also there is some other feature in progress) so it might take a long time (like months), sorry for that.

Patrik

**Comment by angelmanst** [comment]
Thanks for the prompt feedback and for the great project. 
I won’t be able to help much on fixing but I’ll try to help on testing and suggesting new features ;-)

**Comment by bpatrik** [comment]
sure, thats ok. It should not take much time to fix them and its good enough that you made a nice bug report. :)

**Comment by bpatrik** [comment]
Hi,

It turns out that this issue is relatively complex.

According to this: https://stackoverflow.com/a/36593389/10506897, and the official css specification: https://www.w3.org/TR/css-images-4/#the-image-orientation : browsers should support the auto image rotation based on exif data, but only firefox implements it.

Unfortunately, there isn't any nice solution to the problem currently.
I've made an update to the page, that it rotates the photos on client side with these commit: [92fca05](https://github.com/bpatrik/pigallery2/commit/92fca05b2233b026980072fdf3b0833b9fdde482) - [205f98e](https://github.com/bpatrik/pigallery2/commit/205f98e6541a2e6d656cc893da7ee264f041c2a1). It will be part of the next release.

Since the rotation happens on the client side, it might take a while. The page might not respond to any click during the process that might take up a 1-2s /photo.
If most of your photos need to be rotated it might be noticeable. If you have only a small fraction of your photos need to be rotated, it should be fine.

I can suggest you to use a 3rd party apps (like photoshop lightroom) to batch rotate your photos based on their exif tags. (Converting your photos also saves you some storage too.)
