### ISSUE TITLE
Allow running Docker container as specified user

### ISSUE THREAD

**Issue by stumpylog** [bpatrik/pigallery2#138]
**Is your feature request related to a problem? Please describe.**
I would like to be able to run the pigallery2 only (and maybe the full Nginx stack) as a specific user, rather than as root.  Currently, when I set the `user` value, the container is unable to bind port 80 (inside the container).

**Describe the solution you'd like**
I would like to see the `user` configuration option.  Or something like how the containers from linuxserver.io are somehow able to remap user.

**Describe alternatives you've considered** (optional)
I did attempt to mount the volume `/etc/passwd:/etc/passwd:ro`, just in case that could help.

**Comment by bpatrik** [comment]
Hi,

I have only limit experience with non root docker, I'm not sure what happens if you create a container with a non root user.
Also binding to port 80 requires root privileges as far as I know.

I solution / workaround to your problem can be to change the port of pigallery within docker and forward proper new port from docker to the host.
You can do so by setting env variable `PORT` to an port number of your choice,  when you start the container. (You can read more about the possible settings in [MANPAGE.md](https://github.com/bpatrik/pigallery2/blob/master/README.md). It is for the nightly build, but mostly works on the stable version too)

**Comment by stumpylog** [comment]
The logs report this:

```
using config path:/app/data/config/config.json
2/12/2020, 10:08:42 PM[INFO] [JobManager] Running job schedules
2/12/2020, 10:08:42 PM[ERROR] [server] 0.0.0.0:80 requires elevated privileges
```

Thanks for pointing me to the `PORT` settings.  That works great for me when setting the user key in a compose file, when pulling the `pigallery2:latest` tag.
