### ISSUE TITLE
Map will not open

### ISSUE THREAD

**Issue by dddddddavid** [bpatrik/pigallery2#158]
**Describe the bug**
Clicking on the map does not open the map - page freezes and requires a refresh - possibly because of largish gallery (15gb)

Is it possible to disable the map entirely?

**Environment (please complete the following information):**

  OS: Pigallery2 runs on docker on Pi4B (2GB) raspbian buster lite. Proxied from apache server on second Pi4B(4GB) photos in samba shared ssd attached to second pi.

Browser: Firefox for ubuntu 18.04(flawless)

    docker-v3

**Comment by bpatrik** [comment]
Hi, 

yes you can disable all map support in the settings.
Alternatively you can try disabling the thumbnails on the map, and us the pin only. That might help.
You might need to switch to advanced mode in the UI.
And yes it is because of the too many photos in one directory. I would not go above 500.

**Comment by bpatrik** [comment]
I'm closing this due to inactivuty
