### ISSUE TITLE
Face regions not detected

### ISSUE THREAD

**Issue by lbischof** [bpatrik/pigallery2#191]
**Describe the bug**
I am trying to load my own photos into Pigallery2 and get it to recognize my face regions.

I have now downloaded the example photo and modified it by setting a region value (same value):
```
exiftool '-RegionAreaH=0.55270' IMG_6253.jpg
```
But as soon as I modify any tag, it seems that Pigallery2 does not recognize the face region anymore. I tried diffing the exiftool output:
```
$ diff non-working.txt working.txt
144,147c144,147
< [System]        FileAccessDate                  : 2020:10:18 17:10:45+02:00
< [System]        FileInodeChangeDate             : 2020:10:18 17:14:04+02:00
< [System]        FileModifyDate                  : 2020:10:18 17:10:23+02:00
< [System]        FileName                        : IMG_6253_not-working.jpg
---
> [System]        FileAccessDate                  : 2020:10:18 17:09:17+02:00
> [System]        FileInodeChangeDate             : 2020:10:18 17:08:09+02:00
> [System]        FileModifyDate                  : 2020:10:18 17:08:09+02:00
> [System]        FileName                        : IMG_6253_working.jpg
149c149
< [System]        FileSize                        : 889 kB
---
> [System]        FileSize                        : 884 kB
```

**Photo/video (optional) that causes the bug**
Not working:
![IMG_6253_not-working](https://user-images.githubusercontent.com/1837725/96377984-60f82900-1189-11eb-8517-afa38e7a19cf.jpg)
Example image (working):
![IMG_6253_working](https://user-images.githubusercontent.com/1837725/96377985-6190bf80-1189-11eb-9743-9e0a488d3aec.jpg)

**Environment (please complete the following information):**
 - OS: Linux
 - Browser: Firefox

**Used app version**:
- docker-nightly (git hash: acd3cf1fe52038790269cda30454fb21f12d4db4)

**Comment by bpatrik** [comment]
I had a quick look:

From the efix point of view both images seems to contain the face region:
"good": http://metapicz.com/#landing?imgsrc=https%3A%2F%2Fuser-images.githubusercontent.com%2F1837725%2F96377985-6190bf80-1189-11eb-9743-9e0a488d3aec.jpg
"bad":http://metapicz.com/#landing?imgsrc=https%3A%2F%2Fuser-images.githubusercontent.com%2F1837725%2F96377984-60f82900-1189-11eb-8517-afa38e7a19cf.jpg

The faces are loaded here, using `exifreader`:
https://github.com/bpatrik/pigallery2/blob/8c2654980d74cc8735c1ed965fa981f25bfca04e/src/backend/model/threading/MetadataLoader.ts#L209-L247

Interestingly if I debug in it (checking the value of `ret.Regions.value.RegionList.value`), the returned object is way different for the two images:
"Good":
![aaa](https://user-images.githubusercontent.com/7512182/96481327-ad03a600-123b-11eb-9d3a-62af0ef1b493.jpg)
"Bad":
![bbb](https://user-images.githubusercontent.com/7512182/96481323-abd27900-123b-11eb-9948-c9b662168fa2.jpg)

I guess, we should:
1) why is there a difference?
2) If its expected, add a few line of code to MetadataLoader.ts:209 to support the "bad" version too.

Would you be interested looking into it? Otherwise I'll fix it at some point.

**Comment by lbischof** [comment]
https://github.com/mattiasw/ExifReader/issues/129#issuecomment-713131946
> I looked into the code some more and I believe you're correct. There is a bug in the handling of lists where these different ways to represent the same date is just never converted. Unfortunately a fix would be a breaking change. For example, the code referenced in the PiGallery2 ticket you linked would definitely break (the `rdf:Description` should not be exposed like that and would be one of the things that would change). This should of course be fixed but it would then have to go into version 4 which I can't say a timeline for.

I will try to create a pull request so that Pigallery2 supports both versions.
