### ISSUE TITLE
Progressive image loading 

### ISSUE THREAD

**Issue by bkchr** [bpatrik/pigallery2#20]
Hey, do you know https://github.com/schlosser/pig.js? Maybe that is something you could integrate your gallery to make the image loading much nicer :)

**Comment by bpatrik** [comment]
nice lib, thanks. I'll consider adding it in some form. 
Btw, at the image preview window I'm doing something similarly, not that fancy tho.

**Comment by bkchr** [comment]
There is one pull request open that mentions typescript. Maybe that helps you in some way :)
I also have one pull request open, that supports showing images in groups, so it behaves like Google photos.

BTW, the library looks nice so far. Do you have any roadmap?

**Comment by bpatrik** [comment]
well probably I wont be able to use this lib as it is, because I'm too much transformation on the photos, but I could use some part of it.

Well, its only a hobby project for me, I have like 2-3 weeks to work on it every six months.  I don't have anything fix in my mind sofar, but I was thinking about implementing:
 *  `*.md` support, so you can write a little comment to every folder, like a blog.
 * the video support feels a bit buggy, especially on a raspberry, fixing that.
 * face / people recognition - `very future plan`
 * switching google map to openstreatmap
 * dockerizing
