### ISSUE TITLE
Directory is not shown in the search results

### ISSUE THREAD

**Issue by bruce30262** [bpatrik/pigallery2#304]
**Describe the bug**
pigallery2 is not showing the directory in the searching result, an example can be seen in the following URL:

`https://pigallery2.herokuapp.com/search/%7B%22type%22:102,%22text%22:%22emptydirectory%22,%22matchType%22:1%7D`

You can see that while searching for "emptydirectory", the result didn't show the directory we want to search.   

Expected behavior: showing the directory we want to search and allow us to click in and browse the pictures inside the directory.

**Photo/video (optional) that causes the bug**
N/A

**Screenshots**

<img width="851" alt="擷取" src="https://user-images.githubusercontent.com/4478350/119021539-2205ac80-b9d2-11eb-873a-21611b83440c.PNG">

**Environment (please complete the following information):**
 - OS: Window 10 64 bit
 - Browser: Brave 1.24.85 

**Used app version**:
-  v1.8.7 ( The one on https://pigallery2.herokuapp.com/ )
-  Also the latest build from source code ( 0a46388 )

**Comment by bpatrik** [comment]
Yeah I kinda know about the issue:
https://github.com/bpatrik/pigallery2/blob/e5cd8b67248c25197d179963d772a5ba028a9e7d/src/backend/model/database/sql/SearchManager.ts#L183-L185

Although the search work, but it only returns photos within that directory and the `emptydirectory` does not have photos. So I consider this low prio.

**Comment by kagahd** [comment]
@bpatrik, the example of @bruce30262 wouldn't show any photos inside the folder, even it it was not empty, as this [example](https://pigallery2.herokuapp.com/search/%7B%22type%22:102,%22text%22:%22its%20a%20along%20directory%20name.%20with%20special%20caracters(_.-.,-.,)%201234%2056789%20%C5%B1%C3%A1%C3%A9%C3%BA%20%C5%91%C3%B3%C3%BC%C3%B6%22,%22matchType%22:1%7D) demonstrates. 
However, if the quotation marks are omitted, photos inside this folder are shown, as the [example](https://pigallery2.herokuapp.com/search/%7B%22type%22:2,%22list%22:%5B%7B%22type%22:102,%22text%22:%22its%22%7D,%7B%22type%22:100,%22text%22:%22a%22%7D,%7B%22type%22:100,%22text%22:%22along%22%7D,%7B%22type%22:100,%22text%22:%22directory%22%7D,%7B%22type%22:100,%22text%22:%22name.%22%7D,%7B%22type%22:100,%22text%22:%22with%22%7D,%7B%22type%22:100,%22text%22:%22special%22%7D,%7B%22type%22:100,%22text%22:%22caracters(_.-.,-.,)%22%7D,%7B%22type%22:100,%22text%22:%221234%22%7D,%7B%22type%22:100,%22text%22:%2256789%22%7D,%7B%22type%22:100,%22text%22:%22%C5%B1%C3%A1%C3%A9%C3%BA%22%7D,%7B%22type%22:100,%22text%22:%22%C5%91%C3%B3%C3%BC%C3%B6%22%7D%5D%7D) demonstrates. 
Is it because the URL parameter `matchType:1` has been omitted?

I also wonder if it's a good idea to show only the **folder** as @bruce30262 requested, instead to show the folder **content** as it's the case how PiGallery2 works today. Why do you want first to click the folder instead to see immediately its contents? 
Seeing the content immediately is especially useful when the the folder contains subfolders. In such a case, all photos of the searched folder and it subfolders are shown altogether. If I'm not wrong, this behaviour does already what #174 is about, namely **flattening a folder structure from non-root**. Even sorting (ascending or descending) by `date`, `name` or `random` works already.

**Comment by bruce30262** [comment]
> I also wonder if it's a good idea to show only the folder as @bruce30262 requested, instead to show the folder content as it's the case how PiGallery2 works today. Why do you want first to click the folder instead to see immediately its contents?  

So first of all, I use pigallery2 to host my comics and CG collections, which is a little different from hosting photos. Those comics/CG are all stored in different folders ( all in the format of `.jpg`, `.png`...etc ), and if some of them are created by the same author, I'll store those folders into another folder. So it looks something like: 

```
├── CG_collection1
│   ├── pic1.jpg
│   ├── pic2.jpg
│   ├── ...
├── Author1
│   ├── Comic_title_A
│   │   ├── 0.jpg
│   │   ├── 1.jpg
│   │   ......
│   ├── Comic_title_B
│   ├── ...
├── Author2
│   ├── Comic_title_C
│   ├── Comic_title_D
│   ├── ...
```

The whole collection contains hundreds of sub-folder, and that's why the directory searching feature is important to me, since it helps me get to the folder I want to access. A use case will be :   

* I want to watch a comic create by Author1, but I can't remember the title, so I just search "Author1" in the search bar, which will show me the "Author1" directory, then I'll click into the folder and look for that comic.   

> Seeing the content immediately is especially useful when the the folder contains subfolders. In such a case, all photos of the searched folder and it subfolders are shown altogether.

To me it's quite the contrary : It is important to **NOT** showing the pictures altogether in a specific folder because in my case it might show all the comics at once, and I don't want that.  

Right now I'm using an older version of pigallery2 ( [my fork](https://github.com/bruce30262/pigallery2) and [my docker image](https://hub.docker.com/repository/docker/bruce30262/pigallery2) ) which will show the directory in the search results. It would be nice to upgrade to the latest version, however unless it brings back the directory searching or else I guess I'm going to stick with the old version for a little longer :P

**Comment by kagahd** [comment]
@bruce30262, thanks for the description of your use case. I now understand why you need this feature. 
Did PiGallery2 work like you described in the past? Is this the reason that you are using the old version or did you adapt it to your needs? If you are familiar with the code, perhaps you could implement your feature into the newest PiGallery2 version and create a pull request?
It would be nice to have both options though, means, show either the contents of the flatten folder structure or just the clickable folder icon itself.

**Comment by bruce30262** [comment]
> Did PiGallery2 work like you described in the past? Is this the reason that you are using the old version or did you adapt it to your needs?  

Yes the old version does show the directory in the search results ( I'm using the version at 7f321a3ff5ca16c85550 ). I was trying to upgrade to the latest version, however decided not to because I found the directory searching is removed in the latest version.

> If you are familiar with the code, perhaps you could implement your feature into the newest PiGallery2 version and create a pull request?

Unfortunately I'm not familiar with the code ( also not familiar with web app developing ) so I guess it's up to @bpatrik to decide when to bring back the feature. I'm fine with the old version though, since it suits my need and works fine for now.  Again it would be nice to upgrade to the latest version, but I'm also OK with staying in the version I'm using right now :)

**Comment by kagahd** [comment]
@bruce30262 

>I want to watch a comic create by Author1, but I can't remember the title, so I just search "Author1" in the search bar, which will show me the "Author1" directory, then I'll click into the folder and look for that comic.

I might have found a workaround for such a use case but maybe you have others. 
My suggestion: 

1. Search for "Author1"
2. PiGallery2 will show all photos of folder "Author1" and its subfolders altogether
3. Click on one of the photos
4. Click on `info`
5. In the info box, click on the file name
6. PiGallery2 will show only the folder of the clicked photo and the complete path to this folder whereas each path entry (=folder) is clickable. So you would also see your searched "Author1" folder. 
7. Once clicked on "Author1", PiGallery2 will show only subfolders of folder "Authors1", in your example "Comic_title_A" and "Comic_title_B". 

Would this help you?

**Comment by bruce30262** [comment]
@kagahd thanks for providing this workaround ! However although it does work, it's still kinda inconvenient and not as intuitive as the old version, so I think I'm still gonna use the old one.

**Comment by bpatrik** [comment]
Added this functionality with a config switch. By default does not search among folders.

Also updated the docs to explain how one can use the search: http://bpatrik.github.io/pigallery2/

**Comment by bpatrik** [comment]
+1: I can also suggest to tag (keyword) your photos. You can use like exiftool to batch keyword them, but in Windows it is also simple to to select all and add keywords to all of them at once.

**Comment by kagahd** [comment]
I tested the newly added functionality `List directories`. It works really great. Very appreciated, thanks @bpatrik!

**Comment by bruce30262** [comment]
Tested against 77b2d7e and can confirm that `List directories` works really well. Guess it's time to upgrade to v1.9.0 :)   

Since now the directories are being shown I'm closing this issue. A big thank to @kagahd for joining the discussion and @bpatrik for fixing the issue, keep up the good work !
