### ISSUE TITLE
Captions for albums

### ISSUE THREAD

**Issue by zurvan2** [bpatrik/pigallery2#321]
The existing caption support for images reading from the image metadata is great from a UI perspective. Having some way to extend that to videos would be useful. 

Also, having the ability to add captions to albums somewhere/somehow would also be great. Maybe near the top of the layout of images. 

Implementation-wise, maybe both could be solved with some sort of "sidecar" file for metadata? exiftool supports these, for example: https://exiftool.org/metafiles.html I don't know how standard they are.

**Comment by bpatrik** [comment]
There is already an issue for this #156 at least for the video part. 
The app does not support albums (apart from saved search), but I assume you mean folders. 
I do not think that adding metadata to a folder is standard. If you can show an example, I do not mind keeping this issue open. Otherwise I'll close it as the video part is a duplicate.

**Comment by zurvan2** [comment]
For video, XMP sidecars look great. 

I don't think XMP is standard for folders, but I also can't find anything that says XMP sidecars *can't* be used for folders. The "sidecar" concept is pretty open ended to allow use by any file format, I think. 

Something custom like a .pg2conf file would also be an option, but XMP already exists. 

Picking where to *display* it might be harder. Quite a bit of pigallery seems to be modeled after Google Photos (as are a lot of other photo apps). Google photos has a way to show text in albums just in a rectangle, kinda like a single photo, although I think they have heuristics to change the shape of the text box to make it dynamically sized. I'm not asking for anything remotely that complex; I'd be happy with *anything* that puts text in a folder listing, somehow. 

If this isn't possible, or if you just don't want to do it, I'll probably use "convert" or openoffice to create images from text, possibly with additional text as the "caption" of that image, and make it sort to the beginning by using a crazy name. See https://unix.stackexchange.com/questions/138804/how-to-transform-a-text-file-into-a-picture or https://unix.stackexchange.com/questions/395074/imagemagick-convert-text-to-image-readtextimage-assertion

**Comment by bpatrik** [comment]
Sorry, I do not really see this feature happening in the near (next few years) future. 

Its mostly me working on this app in my spare time (when its raining outside and I'm in a mood of coding) and then I usually implement what aligns with my needs. And also, there are 60+ other open issues for this app.

Fur the sake of argument: Why does the name of the folder not good enough as caption? Also folders meant to help structure your files. If they are not doing a good enough job (because they only categorize along one dimension), you can always tag your photos and search those tags (to have an other dimension)

**Comment by zurvan2** [comment]
The use case for albums would be for a sentence or two to describe the "event" that the folder represented. Something like "We spent two weeks at Yosemite. The weather was great for the most part. We really liked the falls at such-and-such." 

Tweet-length, more or less. Just *slightly* more than you can comfortably fit in a filename. 

I have no problem closing this, especially since there's a decent workaround with making a "caption" photo. 

I'd love to chip in, but while I am a developer, I don't know javascript. :( Maybe I'll learn that someday while it's raining! :)

**Comment by bpatrik** [comment]
You might want to follow  this:

I eventually want to add a blog like feature to the app #292:
>Blog-ish feature: Basically the app would recognize README.md files in the folders and would render them once you open a folder in the app. In this case, we could add some notes, stories to the individual folders (like memories about your holidays)

I haven't opened a bug for this yet but I want to do it.
