### ISSUE TITLE
Symlinks on the photos directory break Pigallery2

### ISSUE THREAD

**Issue by tkedwards** [bpatrik/pigallery2#39]
If you have any symlinks in the photos directory (Images folder) you get the following error in the UI:
```
Unknown indexing error for: ./
"[object Object]" 
```
Errors from the logs (from docker logs, I'm using the docker image):

```
1/23/2019, 12:19:26 AM[WARN] Handled error:
ErrorDTO {
  code: 7,
  message: 'Error during listing the directory',
  details:
   { error:
      'Error: ENOENT: no such file or directory, stat \'/pigallery2-release/demo/images/convert_video_to_MP4.sh\'' } }
{ error:
   'Error: ENOENT: no such file or directory, stat \'/pigallery2-release/demo/images/convert_video_to_MP4.sh\'' }
1/23/2019, 12:19:26 AM[WARN] Handled error:
ErrorDTO {
  code: 7,
  message: 'Error during listing the directory',
  details:
   { error:
      'Error: ENOENT: no such file or directory, stat \'/pigallery2-release/demo/images/convert_video_to_MP4.sh\'' } }
```

**Comment by bpatrik** [comment]
Hi,

Thank you for your report. 
Can you give me same more details:
Are you setting your root images folder as a symlink so like: `-v <path to a symlink>:/pigallery2-release/demo/images ` ?  Or you have a *regular* root images folder that contains several symlinks?
Also can you double check if the app has read right on the folder/symlink? 

Patrik

**Comment by tkedwards** [comment]
Hi Patrik,

> Are you setting your root images folder as a symlink so like: -v <path to a symlink>:/pigallery2-release/demo/images ? Or you have a regular root images folder that contains several symlinks?

The root images folder path is a symlink. The problem only happens when I have symlinks inside the root images folder, once I moved the symlinks elsewhere the problem went away

> Also can you double check if the app has read right on the folder/symlink?

The symlinks had 777 permissions, and the app is running in Docker so is effectively root AFAICT

BTW thanks for developing Pigallery2! I searched for ages to find a photo gallery that would work with my existing folders (since I manage the photos using Digikam) and that actually has basic features like video playback and display of comments. Piwigo and Lychee were no good, Nextcloud Gallery is pretty hopeless. Yours is the only one that does things right!

**Comment by bpatrik** [comment]
Hi,

I've checked and the problem seems to be with docker. 
I've also tested it on raspbian with direct install (so no docker) and I could use both folder and file symlinks  within the images folder. 

Here you can read more about the docker's symlink issue:
https://stackoverflow.com/questions/38485607/mount-host-directory-with-a-symbolic-link-inside-in-docker-container

You can try changing the way, you make your image folder accessible by docker, but I cannot really give any guidance with that. Maybe look around here: https://docs.docker.com/storage/

**Comment by tkedwards** [comment]
Thanks, it's annoying Docker can't handle that well. In that case not a pigallery2 issue so I'll close this.

I ended up removing the symlinks from inside the 'photos' directory because they weren't really needed.

**Comment by bpatrik** [comment]
In the mean time I figured that the issue with the symlinks are probably
that the path to the folder might point outside of the mounted volume. (or
the path to the linked folder is different within the docker)

You can try the following:
1) mounting your whole host or a larger set of your host like `-v
/:/hostroot` (not sure if you can mount the whole `/`
2) changing the path to the image folder settings within the app.

I haven't tested it.

Best,
Patrik

**Comment by tkedwards** [comment]
Thanks, that's probably it since the symlinks were to a folder outside of the 'photos' folder

**Comment by peterge1998** [comment]
Hey, I just found this issue.
I am having problems getting PiGallery2 working with symlinks.

My idea was to create a folder in the Nextcloud folder, where I can sync my photos from my iPhone to.
Then I would like to display them in PiGallery2, that's why I linked the folder from the Nextcloud folder to the folder where PiGallery displays the pictures from with ln -s.

When I want to access the subfolder, where the images are in, I get this error:
![image](https://github.com/bpatrik/pigallery2/assets/47355238/b0bdf873-326f-4913-bf07-75cf810d825c)

My version is latest_2.0.11.

**Comment by ki9us** [comment]
> Thanks, that's probably it since the symlinks were to a folder outside of the 'photos' folder

I got this error for this reason too.  

Feature request: 

 1. Catch such errors instead of crashing
 2. Log something like "[WARN] Broken symlink at /app/data/images/myphoto.jpg"
