### ISSUE TITLE
Large index of photos, Thumbnail generation: JavaScript heap out of memory

### ISSUE THREAD

**Issue by kardo22** [bpatrik/pigallery2#494]
I am testing this application because it seems very lightweight. I have ran into issues after indexing over 2,5 million files and finally gone to do some thumbnail generation, it seems it eats too much memory trying to queue up all those files to be generated so it crashes before the thumbnail generation can even begin.

From the docker logs:

`5/27/2022, 10:17:33 AM[[32mINFO_[0m][JOB] Running job : Thumbnail Generation

FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
1: 0xa3aaf0 node::Abort() [node]
2: 0x970199 node::FatalError(char const*, char const*) [node]
3: 0xbba45e v8::Utils::ReportOOMFailure(v8::internal::Isolate*, char const*, bool) [node]
4: 0xbba7d7 v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, bool) [node]
5: 0xd769e5 [node]
6: 0xd7756f [node]
7: 0xd853ab v8::internal::Heap::CollectGarbage(v8::internal::AllocationSpace, v8::internal::GarbageCollectionReason, v8::GCCallbackFlags) [node]
8: 0xd88f6c v8::internal::Heap::AllocateRawWithRetryOrFailSlowPath(int, v8::internal::AllocationType, v8::internal::AllocationOrigin, v8::internal::AllocationAlignment) [node]
9: 0xd5764b v8::internal::Factory::NewFillerObject(int, bool, v8::internal::AllocationType, v8::internal::AllocationOrigin) [node]
10: 0x109fc0f v8::internal::Runtime_AllocateInYoungGeneration(int, unsigned long*, v8::internal::Isolate*) [node]
11: 0x1448e19 [node]`

App version: v1.9.3 running on docker @ unraid 6.9.2

Any ideas how to tackle this? Thanks.

**Comment by UnreleasedCode** [comment]
I have just around 35000 pictures in my pigallery. I have a similar heap out of memory problem. Indexing is working, afterwards the container crashes with:

pigallery2    | 9/3/2022, 5:23:55 AM[INFO_][JOB] Running job : Indexing
pigallery2    | 9/3/2022, 5:25:43 AM[INFO_][JOB] Job finished: Indexing
pigallery2    |
pigallery2    | <--- Last few GCs --->
pigallery2    |
pigallery2    | [1:0x5f78b80]   275511 ms: Mark-sweep (reduce) 2046.7 (2051.2) -> 2046.2 (2052.7) MB, 1069.4 / 0.0 ms  (average mu = 0.524, current mu = 0.006) allocation failure scavenge might not succeed
pigallery2    | [1:0x5f78b80]   276788 ms: Mark-sweep (reduce) 2047.2 (2054.7) -> 2046.8 (2055.2) MB, 1270.5 / 0.0 ms  (+ 0.0 ms in 15 steps since start of marking, biggest step 0.0 ms, walltime since start of marking 1277 ms) (average mu = 0.335, current mu = 0.005) all
pigallery2    |
pigallery2    | <--- JS stacktrace --->
pigallery2    |
pigallery2    | FATAL ERROR: MarkCompactCollector: young object promotion failed Allocation failed - JavaScript heap out of memory
pigallery2    |  1: 0xa3aaf0 node::Abort() [node]
pigallery2    |  2: 0x970199 node::FatalError(char const*, char const*) [node]
pigallery2    |  3: 0xbba45e v8::Utils::ReportOOMFailure(v8::internal::Isolate*, char const*, bool) [node]
pigallery2    |  4: 0xbba7d7 v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, bool) [node]
pigallery2    |  5: 0xd769e5  [node]
pigallery2    |  6: 0xda737e v8::internal::EvacuateNewSpaceVisitor::Visit(v8::internal::HeapObject, int) [node]
pigallery2    |  7: 0xdb33b6 v8::internal::FullEvacuator::RawEvacuatePage(v8::internal::MemoryChunk*, long*) [node]
pigallery2    |  8: 0xd9f54f v8::internal::Evacuator::EvacuatePage(v8::internal::MemoryChunk*) [node]
pigallery2    |  9: 0xd9f7c8 v8::internal::PageEvacuationTask::RunInParallel(v8::internal::ItemParallelJob::Task::Runner) [node]
pigallery2    | 10: 0xd920a9 v8::internal::ItemParallelJob::Run() [node]
pigallery2    | 11: 0xdb5310 void v8::internal::MarkCompactCollectorBase::CreateAndExecuteEvacuationTasks<v8::internal::FullEvacuator, v8::internal::MarkCompactCollector>(v8::internal::MarkCompactCollector*, v8::internal::ItemParallelJob*, v8::internal::MigrationObserver*, long) [node]

**Comment by bpatrik** [comment]
35k photos should work. I'm running it with 60k-70k photos. 

Can you enable full debug logs to see what is it actually doing?

*    Set env variable NODE_ENV=debug to log everything.
*    To get logs from docker: docker ps -a to list containers, docker logs <container ID> to get logs.

**Comment by bpatrik** [comment]
The latest commit should fix the original issue.

**Comment by UnreleasedCode** [comment]
Exposes the problem were some empty files in my image dir.

`pigallery2    | 2/26/2023, 12:41:53 PM[DEBUG][MetadataLoader] Error parsing exif /app/data/images/IMG_20180919_145407.jpg Error: Empty file
pigallery2    |     at syncFileToBuffer (/app/node_modules/image-size/dist/index.js:77:19)
pigallery2    |     at imageSize (/app/node_modules/image-size/dist/index.js:112:24)
pigallery2    |     at /app/src/backend/model/threading/MetadataLoader.js:179:69
pigallery2    |     at FSReqCallback.wrapper [as oncomplete] (node:fs:681:5)`

**Comment by martadinata666** [comment]
I'm commenting becaue after reorganizing photos java heap OOM triggered, when a whole folder contains about 13k not trigger heap OOM, but after reorganizing folder, split 13k photos into respective name, it triggered oom. May you look into it again?

Thanks.
