### ISSUE TITLE
'Invalid CSRF token'

### ISSUE THREAD

**Issue by ScuttleSE** [bpatrik/pigallery2#514]
**Describe the bug**

Just installed from the docker image, getting this error constantly, both in the log, and as a red popup. I have put the service behind a reverse proxy and am using SSL.

```
7/3/2022, 7:06:46 AM[WARN_] Handled error:
ErrorDTO {
  code: 1,
  message: 'Invalid CSRF token',
  details: ForbiddenError: invalid csrf token
      at csrf (/app/node_modules/csurf/index.js:112:19)
      at result (/app/node_modules/express-unless/index.js:49:5)
      at processTicksAndRejections (internal/process/task_queues.js:95:5) {
    code: 'EBADCSRFTOKEN'
  },
  request: { method: 'POST', url: '/api/graphql' },
  detailsStr: 'ForbiddenError: invalid csrf token'

```

**Comment by ScuttleSE** [comment]
tried with both latest and nightly-alpine tags, same errors

**Comment by bpatrik** [comment]
My guess would be something is trying to call my app (maybe an attack?). 

I do not use graphql, so `/api/graphql` is not a valid url for my app. Therefore whoever calls the app cannot have a valid csrf token, so you et these errors. 
Try looking at some logs at the system or at the reverse proxy.

Also take a look at #214

**Comment by sarayourfriend** [comment]
Considering how common it is for websites to get crawled for easy vulnerabilities (like the heap of spammy requests listed in #214), it's worth considering if a _warn_ level log for these events is correct. In my experience the only warnings worth issuing in production are ones that cannot be otherwise monitored (like unexpected business logic cases). Authentication errors should _not_ cause warnings to be logged... there's nothing someone running the application can do about it that they wouldn't already know based on regular access logs (heaps of 401s to authenticated endpoints, maybe start banning IPs at the CDN level, for example). I'd recommend downgrading the log level for these to info or even debug.

For folks needing to monitor authentication errors in production, you'll see them as 401 responses in your request log, and if it's a real issue, you can change the logging level in production temporarily to debug it.

I've got a PR to share shortly that includes a proposed solution to this, by identifying specific log levels for each error code, defaulting to warning when a level isn't defined.
