### ISSUE TITLE
Alphabetical sort isn't correct for images like 10 and 10.1

### ISSUE THREAD

**Issue by TheAnachronism** [bpatrik/pigallery2#518]
**Describe the bug**

I have a directory with images, and they are just named by numbers. These numbers are the correct order in which the images should be displayed, but some have a .1 or further to show they are other versions of the actual image.  The correct order would be:

- 10
- 10.1
- 10.2

But it shows up as
- 10.1
- 10.2
- 10

**Photo/video (optional) that causes the bug**

These images are quite private, so I'd rather not upload them here.

**Environment (please complete the following information):**
 - OS: Running in docker on an Ubuntu system
 - Browser: Edge

**Used app version**:
- docker-latest

**Comment by bpatrik** [comment]
This is related to #341, #223, #224,  and  #230

**Comment by sarayourfriend** [comment]
I'm looking into this bug to submit a PR to fix it. Just wanted to share I've found that this has something to do with the presence of a file extension, or rather, anything after the ordering part.

Running these following statements in the browser debugger at https://github.com/bpatrik/pigallery2/blob/f05ee7a867419da8aae1eb1087e350c343ba5bb3/src/frontend/app/ui/gallery/navigator/sorting.service.ts#L136

I was confused at first, because I was testing the collator just using `10`, 10.1`, and `10.2`, and it sorts perfectly:

```js
>>> ["10.1", "10.2", "10"].sort(this.collator.compare)
Array(3) [ "10", "10.1", "10.2" ]
```

I put the debugger in to see if I was understanding the code correctly, and realised the media names all have the extension (naturally):

```js
>>> media.map(a => a.name)
Array(25) [ "_0004.jpg", "10.1.jpg", "10.2.jpg", "10.jpg", "broken image.JPG", "bunny.mp4", "Chars_exiftool.jpg", "IMG_6220.jpg", "IMG_6253.jpg", "IMG_6263.jpg", … ]
```

And yeah, sure enough, when you add the file extension, the sorting is as described.

```js
>>> ["10.1.jpg", "10.2.jpg", "10.jpg"].sort(this.collator.compare)
Array(3) [ "10.1.jpg", "10.2.jpg", "10.jpg" ]
```

To fix this, it seems like we'd just want to trim the extension at sort time? I don't know if that's reliable, but I'll get a PR up for it shortly.
