### ISSUE TITLE
View and edit shared links

### ISSUE THREAD

**Issue by mcdamo** [bpatrik/pigallery2#55]
A UI to list the shared links that have been created would be useful.
As would being able to update the parameters for a share, such as change password or expiry, or delete the shared link immediately.

Alongside these controls it might be helpful to allow the user to give "names" to the shared links so that the user has a way to identify them easier in the UI.

**Comment by bpatrik** [comment]
Thank you for the suggestion.

I'll consider adding these in the future. 
Currently I'm working on some other part of the project, so I cannot give you any deadline about it. (It will take up months most likely.) 
If there are features that have more 'vote' (i.e.: thumbs up) on them, I give them a higher priority.

**Comment by tkedwards** [comment]
Is there a way to remove shared links in the meantime?

**Comment by bpatrik** [comment]
Currently not unfortunately. Only by directly editing the Mysql DB.
And also they have an expiration date.

**Comment by mcdamo** [comment]
There is now a UI for listing and deleting shared links.

**Comment by faustusdotbe** [comment]
This seems like the best place to ask about this short of opening a new issue/feature request. 

Is there a way to edit the URL of shares? Currently they are generated automatically to eg `domain.tld/share/some-auto-key`, but `some-auto-key` is not easy to remember. It would be very cool if instead of the random key we could manually specify a string of our own. 

Thanks

**Comment by bpatrik** [comment]
no there is no such method available at the moment.

**Comment by bpatrik** [comment]
It should be in the setting when you are in advanced mode.
