### ISSUE TITLE
"To The Top" button when scrolling down

### ISSUE THREAD

**Issue by kardo22** [bpatrik/pigallery2#615]
**Is your feature request related to a problem? Please describe.**
You can do a lot of scrolling in PiGallery if you have many images, a great way to navigate would be to add a simple "Top" button that only appears if you scroll down.

I added this myself via a simple CSS but i am sure someone with better coding knowledge could do a nicer one, but this is how it looks for me when i scroll down (See bottom right corner for the top button):

![image](https://user-images.githubusercontent.com/106375298/219658945-a479249e-aaf3-4ce0-ad19-0c99599aaa5a.png)

I added this by adding CSS to the gallery via custom HTML head:

`<style>#myBtn{display: none; position: fixed; bottom: 20px; right: 30px; z-index: 99; font-size: 18px; border: none; outline: none; background-color: red; color: white; cursor: pointer; padding: 15px; border-radius: 4px;font-weight:bold;text-transform:uppercase;}#myBtn:hover{background-color: #555;}a.nav-link{display:none;}</style><button onclick="topFunction()" id="myBtn" title="Go to top">Top</button><script>var mybutton=document.getElementById("myBtn");function scrollFunction(){document.body.scrollTop>20||document.documentElement.scrollTop>20?mybutton.style.display="block":mybutton.style.display="none"}function topFunction(){document.body.scrollTop=0,document.documentElement.scrollTop=0}window.onscroll=function(){scrollFunction()};</script>`

**Comment by kagahd** [comment]
Nice, thanks @kardo22 
As for me, it only worked when I moved the last closing tag `</script>` at the begin before the tag `<style>` because PiGallery2 enclosed the custom HTML within a `<script></script>` block. Hence, the `</script>` tag at the beginning of the custom HTML code closes PiGallery's `<script>` block while PiGallery's closing `</script>` tag closes the custom HTML code.
I'm using the latest PiGallery2 version (1.9.5). Which one are you using @kardo22 ?

**Comment by kagahd** [comment]
I just saw that the custom HTML code enclosing `<script></script>` block has been already addressed by you, @kardo22, in #611

**Comment by bpatrik** [comment]
This or similar issues are long lasting: #427, #44, #27.

I had to wrap the HTML inject part within script tags otherwise angular webpack gave some error (forgot what was the actual issue).

With #587. I'm planning to rescturcture the top bar to appear on scroll up and be more phone friendly. Hopefully that will also obsolete the scroll up button. Or alternatively I can also add a scroll up button that would float in when you start scrolling up.

**Comment by bpatrik** [comment]
Latest commit should support this. see https://github.com/bpatrik/pigallery2/commit/b7529b13e10f283ecf0b26d3c6aee7d12a936a3b
