### ISSUE TITLE
Same day search

### ISSUE THREAD

**Issue by bpatrik** [bpatrik/pigallery2#660]
Tracking bug for enabling same day search like:

```
same-day:every-week
same-day:every-week
same-day:every-month
same-day:every-month
same-day:every-year
same-day:every-year
same-day:1-days-ago
same-day:1-days-ago
same-day:1-weeks-ago
same-day:1-weeks-ago
same-day:1-months-ago
same-day:1-months-ago
same-day:1-years-ago
same-day:1-years-ago
last-4-days:every-week
last-4-days:every-week
last-4-days:every-month
last-4-days:every-month
last-4-days:every-year
last-4-days:every-year
last-4-days:1-days-ago
last-4-days:1-days-ago
last-4-days:1-weeks-ago
last-4-days:1-weeks-ago
last-4-days:1-months-ago
last-4-days:1-months-ago
last-4-days:1-years-ago
last-4-days:1-years-ago
```

**Comment by bpatrik** [comment]
This feature is mostly done. I made some unit tests, but pretty sure its buggy a bit on the edges (like day boundaries), but seems to work in the big picture. 

Feel free to report bugs if you find any.

**Comment by ltctceplrm** [comment]
Oh man this is cool to see, I'm glad I checked the github issues because this is a feature I've wanted to have for a while!

Is it best to open a new issue for bugs? I think I've encountered the day boundary problem you mention, it doesn't recognize some photos as being on the same day even though they're from 2022-07-24 and 2020-07-24, for now I'm "solving" it by using `last-1-days:every-year` because then they do show up but so do photos from 2021-07-23.

Other than that **it's a really great feature** that I was actually trying to implement using a bunch of daisy chained AND OR saved searches but that wasn't going anywhere (I think the search feature wasn't built with that in mind). `(after:2018-11-11 and before:2018-11-12) or (before:2022-11-12 and after:2022-11-11)`

Together with the random image URL I now have a tasker profile that send me a daily "On this day" notficiation that I can I click it it opens the pigallery2 url.

pigallery2 is the best gallery software I've come across and I've tried out lots of them. It's also the only one that's fully compatible with my digikam workflow so thank you for your continued work on this software.

**Comment by bpatrik** [comment]
Ah great. This keywords were actually created for the same use-case. See #683 for more details.

**Comment by bpatrik** [comment]
The last commit should resolve it (hopefully). Date boundary is not necessary a straight forward problem. It also depends on the server and photo timezone which can be unexpected if the client is not in the server's timezone. I think its fine to have a good enough solution here.
