### ISSUE TITLE
Suggestion: Offer a dark theme

### ISSUE THREAD

**Issue by wechsler42** [bpatrik/pigallery2#68]
Thanks a lot for your effort on pigallery2. I use it on a AMD64 NAS with Debian 9.

I would like to suggest a to implement a dark theme additional to the the white (light) theme. So a user could choose between the two themes.

**Comment by bpatrik** [comment]
Hi 
Thank you for the suggestion. I'll add this to the app at some point (sorry no deadly promise, probably it will take up several months, until I get there)

Best,
Patrik

**Comment by barry-luijten** [comment]
HI,

I have been looking for ways to implement this and there seem to be several options:
1. Since pigallery2 uses bootstrap 4 today, we could use bootstrap sass variables in scss files which can be compiled at build time and switched at runtime. Example: https://github.com/maychan111/ng-multi-bootstrap-themes

2. The other option I have been reading about, is using CSS variables, combined with a theme service component. Example: https://coryrylan.com/blog/theming-angular-apps-with-css-custom-properties

Option 2 is a more "Angular"-approach and might also work with the CSS variables that bootstrap uses (for instance --primary and --secondary). It's also more elegant than the javascript in the example of option 1, which enables or disables a compiled stylesheet by manipulating <link> elements in the html head. 

What do you guys think? I would like to give it a shot, if that's OK with you?

**Comment by bpatrik** [comment]
Hi,

Thank you for your research.

1. I'm not in favor of the first option, as it feels hacky with the basic js files, like: https://github.com/maychan111/ng-multi-bootstrap-themes/blob/master/src/js/style-switcher.js

2. the second is more promising!
I was thinking about that it would be great if we could add a class to the body, like `<body class="dark-theme"..`  (or to the `<app-pi-gallery2 class=...>`). To solve the whole thing. In that case if necessary we can also prerendered the theme class on server side.
(There might be some theme flickering between the first page render and the service load. Prerendering on server side, we can show the correct theme  even before the angular loads. This might not be an issue, but at least there is a possibility to solve.  For that we need store the theme in cookies. )

btw I did not know about the possibility of css variables :/, so the current primary and secondary color are hardcoded in some  css files.

The project is on angular v8 and unfortunately it is not possible to upgrade it right now (until angular can properly extract localize values from `*.ts`, see: https://github.com/angular/angular-cli/issues/16375)

-----------------------
I would be happy if you can add this to the project. 
The workflow for development is: 
 1. compile angular part: `npm run run-dev` (it compiles and watches for changes) 
 2. compile common and backend folders `npm run build-backend` or `tsc -w` (most IDEs do it by default)
 3. run backend `npm start`
If you contribute to the project please use/import `.editorconfig` and `tslint` (WebStorm import them more or less automatically). And try avoid adding too many new dependencies (adding devdependencies are fine)

----------------
A short disclaimer: So this is my hobby project that I'm using on my raspberry and sharing with the public so others can benefit form it too. It is not necessary meant to 'change the word' :) but more to serve my needs. What I'm trying to say: I'm happy to see controbutions to the projects that meet my plans (like changing themes), otherwise I cannot grantee that I'll be able to merge them.

**Comment by barry-luijten** [comment]
Hi, sorry, it has been a while, but I have just created a PR which may implement this feature. Please let me know what you think!

Best regards,
Barry

**Comment by bpatrik** [comment]
Hi, sorry for not responding yet. I started to work for a new company with strick regulation on free time/hobby projects. I'm trying to figure out what is possible and what is not. Might take a few weeks because of COVID-19.

**Comment by bpatrik** [comment]
As part of this I will also implement minimal customizing ability. New tracking bug: #642. Lets continue there.

**Comment by bpatrik** [comment]
This is now available.
