### ISSUE TITLE
[Help requested]: New icon

### ISSUE THREAD

**Issue by bpatrik** [bpatrik/pigallery2#690]
With my UI improvements effort I'm thing updating the App icon.
The requirements: 
1. It should be black&white svg icon. 
2. Should represent: pigallery2 
   1.  Should show its a photo (and a bit also video) gallery. 
   2.  Should show some raspberry pi icon styles. (I'm considering dropping it. As the app is not only for RPI. What more I might also change my hardware)
3. Should be recognizable in a very small size (i.e.: On the browser tab).
   i. Like just how the github icon works. 

I'm not a designer, so I'm struggling with it a bit. I had the following doodles so far: 

a)<img src=https://github.com/bpatrik/pigallery2/assets/7512182/28106173-2c28-4b90-af01-0e0256377d5f width="100px" />,b)<img src=https://github.com/bpatrik/pigallery2/assets/7512182/2e75f3c9-6e7d-4256-8007-fc5592d2b00af width="100px" />,c)<img src=https://github.com/bpatrik/pigallery2/assets/7512182/f8e53a28-7779-465b-8c7e-dd892218238b width="100px" />,d)<img src=https://github.com/bpatrik/pigallery2/assets/7512182/c3401351-f513-4536-b444-e39c8a07a256 width="100px" />,e)<img src=https://github.com/bpatrik/pigallery2/assets/7512182/a8b5539a-c7f9-4854-bf11-a596e792585d width="100px" />,f)<img src=https://github.com/bpatrik/pigallery2/assets/7512182/f4c078eb-8ba2-46b5-89c1-c0e73cb9050c width="100px" />,g)<img src=https://github.com/bpatrik/pigallery2/assets/7512182/b6107a75-bd29-4f98-929c-b634d0509816 width="100px" />,h)<img src=https://github.com/bpatrik/pigallery2/assets/7512182/56ececa6-f803-4c3b-a1a0-40fb6dd45ec6 width="100px" />,i)<img src=https://github.com/bpatrik/pigallery2/assets/7512182/91695dcf-d651-423c-8a66-60c00068840a width="100px" />,j)<img src=https://github.com/bpatrik/pigallery2/assets/7512182/3df45733-53c8-4a71-bcba-479c133ce665 width="100px" />,k)<img src=https://github.com/bpatrik/pigallery2/assets/7512182/608b6eff-2c49-425e-a66b-7e09644361e5 width="100px" />,

Anyone has any better idea, suggestion? Of course i) is the current icon.

Disclaimer: Since the icon is a signature element of an app and design is subjective, I'm not making any promises on changing the icon, but I'm open to have something nice :)

**Comment by mrtnbr** [comment]
Hm, also not a designer, but I will share my thoughts.

From the ones you made, I like C best, second place F.

For my selfhosted app dashboard I use the following two icons for pigallery2 (I run two instances). I think the two above are much better though.
mdi-image-multiple-outline
mdi-folder-multiple-image 

I have never run pigallery2 on a raspberry pi, but always as a container on a more traditional, more powerful server.

**Comment by bpatrik** [comment]
Thanks @mrtnbr. Just to clarify, this is what you are referring to: https://pictogrammers.com/library/mdi/icon/image-multiple-outline/ , right?

**Comment by mrtnbr** [comment]
Yes, took a screenshot to show them both:

![pg2_icons](https://github.com/bpatrik/pigallery2/assets/4752390/8498ac9b-d358-45fd-9a38-a7e4fc0fbb56)

**Comment by netlands** [comment]
I can however understand the idea of changing it to something more photo or camera-oriented. This makes sense. 

The icons using either a camera or picture lack uniqueness. They look like regular UI icons with an added (leaf) accent and do not make a good product logo. I would avoid re-using any regular icon in "rebranding".

Since the app focuses on photos (in a library) on a Raspberry Pi icons (b) and (a) have a very good feeling (of balance) to it.
(b) keeps some very recognizable parts of the raspberry. It is a gallery (photo organizing app) built for Pi. The shutter lines make it clear enough that it is a new logo related to a camera. One note the thin shutter lines could be a little more even-sized to make them easier to see.  
(a) might be associated with a Christmas decoration (my opinion ;)

(b) additionally has the benefit that existing users will immediately recognize it as the current black-and-white Raspberry Pi logo has been used until now.

From the suggestions, I would go for (b) with slight adjustments to the lines.

P.S. I am not a designer by any means, but have some experience with (traditional) Japanese kamon (family crest) designs. These are mostly small (often circular) monochrome stylized images that have stayed nearly identical for a very long time. They commonly have a strong symmetrical and balanced design that feels just right.

**Comment by bpatrik** [comment]
thank you for your input. Unfortunately it came a bit late, I already spend time on improving f). (as f) was the union of the list of icons that several of my friends liked).
Also have a nice curves that the new design also follows, so the design style goes well with the app.

I like your arguing and I agree with that a more unique and creative icon would do better for the branding. 

I'm considering doing an other re-branding in the future with name change. I will then probably take a look again into designing a new logo. 

Now the logo is not as hard-coded as you can change them in the settings if you have an svg that the app supports.
