### ISSUE TITLE
urlBase configuration not working

### ISSUE THREAD

**Issue by alexkoon** [bpatrik/pigallery2#695]
I have configured urlBase to have '/photos/' and expect accessing www.mydomain.com/photos to show the home page of PG2. However, I get the text Not Found in the browser. Having also set the log level to 'debug' the log shows 

GET /photos 404 
GET /photos/ 404

I am running version 1.9.5 in docker and have configured traefik proxy to route www.mydomain.com/photos to PG2 - this is working as described above, but PG2 is ignoring or not making necessary adjustments with the urlBase. 

I already have a PG2 instance working fine without a urlBase configured using photos.mydomain.com.

**Comment by Rickkwa** [comment]
I think the issue might be with your traefik configuration. The urlBase is probably used just for generating links.

**Comment by alexkoon** [comment]
So to clarify and help me understand, the urlBase is used internally by PG 2 to generate correct links. It is up to the proxy to strip the base url before forwarding the request to PG2? For example, if I have https://www.mydomain.com/photos/gallery, the reverse proxy will use its internal rules and route this to PG2, and in the process strip away the base URL and pass https://www.mydomain.com/gallery to PG2?

**Comment by Rickkwa** [comment]
So you have traefik running and listening on port 80/443 of `www.mydomain.com` presumably. Then you have PG running, for example, on an internal IP port 8080. You'll want traefik configuration so that you have  `https://www.mydomain.com/photos/<path>` proxying the request to `<PG>:8080/<path>`.

The urlBase is to make it so that the links generated on app will be `https://www.mydomain.com/photos/*` instead of `https://www.mydomain.com/*`, since the latter won't match the traefik routing rules and get routed to some other app.

**Comment by alexkoon** [comment]
Thanks - got it to work. In essence
www.mydomain.com/photos is routed by the reverse proxy to PG 2.
As part of the routing, configure the reverse proxy to strip the /photos from the url.
