### ISSUE TITLE
Suggestion: Support video playback for .mts and .m2ts (AVCHD) clips

### ISSUE THREAD

**Issue by wechsler42** [bpatrik/pigallery2#71]
Hi there,
besides the support videos in mp4, ogg, ogv, webm format I would like to suggest adding support for .mts and .m2ts video clips. These two formats  are used by some cameras and camcorders of e.g. Sony, Lumix, etc. (see: [AVCHD](https://en.wikipedia.org/wiki/AVCHD)).

**Comment by bpatrik** [comment]
Hi,

Unfortunately, only mp4, WebM and Ogg files are supported in the browser. [More details here.](https://www.w3schools.com/html/html5_video.asp) I cannot really do anything to fix it.

A more detailed answer tho this issue here: https://github.com/bpatrik/pigallery2/issues/66#issuecomment-488240044 . 

In short:
I'm actually planning to make it possible to reconvert original photos/videos, so that I can support more extensions (like raw photos, .mov-s, etc..).
Read more about this idea here #66 and here #50 .

Best,
Patrik

**Comment by bpatrik** [comment]
Hi,

The app now supports video transcoding with ffmpeg. 
Therefore more video formats are supported.
See the full list here: https://github.com/bpatrik/pigallery2/blob/f2faa4cd25be53dd76ce750ea05f3181652f758d/src/common/SupportedFormats.ts#L21-L39

Please note that transcoding should be done manually in the settings. (or schedule it in advanced setting mode)

Best,
Patrik
