### ISSUE TITLE
How to "update" config.json

### ISSUE THREAD

**Issue by rhatguy** [bpatrik/pigallery2#758]
What is the preferred way to "upgrade" the config.json?  The file was created when I first installed pigallery2 but there has been drift in the "default" config since then.  For example, I have a job named "preview filling" in my config.json that fails every time I run it, and is not there in the example man page anymore.  Is it up to the user to manually update their config by either generating a new config and re-applying any custom settings or am I missing something?

**Comment by bpatrik** [comment]
There is no official config update. 
I usually just delete those entries from the config that there app has a problem with, so that I do not loose my custom settings. Note: If you do not specify something in the config, that falls back to the def. value, so its safe to delete from the config. 
Alternatively you can justdelete the whole config.

Preview filling was renamed to something like cover filling.

**Comment by rhatguy** [comment]
Just to close the loop on this, I removed the jobs section from my config.json and restarted the container.  Jobs reverted back to default.  I reset my indexing job to run every day at 2 AM, and when I saved that, the jobs section was re-written with updated jobs into the config.json file.  

Closing this.  Thanks!
